package com.onlinevehicleservicemanagement.projectvehicleservicemanagementsystem.Repository;
import com.onlinevehicleservicemanagement.projectvehicleservicemanagementsystem.Model.Vehicle;
import org.springframework.data.jpa.repository.JpaRepository;
public interface VehicleRepository extends JpaRepository<Vehicle, Long> {}